import {
  AnalyticsConsent,
  AnalyticsEventName,
  AnalyticsEventPropertiesMap,
} from '@easy-genomics/shared-lib/src/app/types/analytics';
import { useAnalyticsStore } from '@FE/stores';

/**
 * Privacy-safe upstream analytics composable.
 *
 * This is the ONLY place that talks to the analytics SDK. It is intentionally
 * driver-shaped (PostHog today) so swapping providers is a one-file change.
 *
 * Identifier rules are enforced here, never per call-site:
 *  - every id passed to {@link hashId} is one-way SHA-256 hashed together with
 *    the per-deployment salt, so raw ids never leave the browser and the same
 *    person at two deployments hashes to two unrelated values. NB: the salt is
 *    shipped in the bundle, so it is not secret from someone who loads this
 *    deployment's app — the hashing gives cross-deployment unlinkability at the
 *    central project, not protection against a local attacker re-identifying an
 *    id they can already see in this deployment's UI (see docs/deployment/analytics.md);
 *  - no event is ever sent unless BOTH the institution opted in
 *    (ANALYTICS_ENABLED) AND the end user granted consent;
 *  - analytics is force-disabled when DNT / GPC is set, in dev, or on
 *    auth pages whose URLs can contain emails.
 */

// Minimal shape of the PostHog browser SDK we rely on. Typed loosely so the
// package only needs to exist at build time and can be swapped out easily.
interface PostHogLike {
  init: (apiKey: string, options: Record<string, unknown>) => void;
  capture: (event: string, properties?: Record<string, unknown>) => void;
  identify: (distinctId: string, properties?: Record<string, unknown>) => void;
  reset: () => void;
  register: (properties: Record<string, unknown>) => void;
  group: (groupType: string, groupKey: string) => void;
  opt_in_capturing: () => void;
  opt_out_capturing: () => void;
}

// Project-level PostHog public key. Owned by the Easy Genomics project (a single
// central PostHog project receives events from every participating deployment).
const POSTHOG_PROJECT_API_KEY = 'phc_zUBGLiMbT6psuFLnsREmHERKAXehsRUdt8qLt57WrAof';
// PostHog ingestion host (US region). Events are sent directly to PostHog.
const POSTHOG_API_HOST = 'https://us.i.posthog.com';
// PostHog UI host used for links generated by the SDK.
const POSTHOG_UI_HOST = 'https://us.posthog.com';

// Module-level singletons shared between the plugin and every composable call.
let posthog: PostHogLike | null = null;
let initInFlight: Promise<PostHogLike | null> | null = null;

function isBrowser(): boolean {
  return typeof window !== 'undefined';
}

/** True when Do-Not-Track is set by the browser. */
function isDoNotTrack(): boolean {
  if (!isBrowser()) return false;
  const nav = window.navigator as unknown as { doNotTrack?: string; msDoNotTrack?: string };
  const win = window as unknown as { doNotTrack?: string };
  const dnt = nav.doNotTrack || win.doNotTrack || nav.msDoNotTrack;
  return dnt === '1' || dnt === 'yes';
}

/** True when Global Privacy Control is set by the browser. */
function isGlobalPrivacyControl(): boolean {
  if (!isBrowser()) return false;
  return (window.navigator as unknown as { globalPrivacyControl?: boolean }).globalPrivacyControl === true;
}

/**
 * Routes whose URLs can contain emails as query params. The banner is suppressed
 * and analytics is forced off on these.
 */
const SENSITIVE_ROUTE_PREFIXES = ['/signin', '/forgot-password', '/reset-password', '/accept-invitation'];

function isSensitiveRoute(): boolean {
  if (!isBrowser()) return false;
  const path = window.location.pathname || '';
  return SENSITIVE_ROUTE_PREFIXES.some((prefix) => path.startsWith(prefix));
}

/** Masks UUID-like and long numeric path segments so URLs cannot identify a lab/run/user. */
function sanitizePath(path: string): string {
  return path
    .split('/')
    .map((segment) => {
      if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(segment)) return ':id';
      if (/^\d{6,}$/.test(segment)) return ':id';
      return segment;
    })
    .join('/');
}

/**
 * Reduces a URL to a sanitized pathname only. Drops the origin (so the
 * hostname/domain — which would identify the deployment/institution — never
 * leaves the browser), strips the query string and fragment (which can carry
 * emails on auth routes), and masks identifying path segments. Falls back to
 * treating the input as a bare path when it is not an absolute URL.
 */
function sanitizeUrl(rawUrl: string): string {
  try {
    const url = new URL(rawUrl);
    return sanitizePath(url.pathname);
  } catch {
    const [pathOnly] = rawUrl.split(/[?#]/);
    return sanitizePath(pathOnly);
  }
}

/**
 * PostHog auto-attaches several properties that contain the hostname/domain
 * (which would identify the deployment). They carry no analytics value for us,
 * so they are dropped entirely rather than sanitized.
 */
const HOST_BEARING_PROPERTIES = [
  '$host',
  '$referring_domain',
  '$initial_host',
  '$initial_referring_domain',
  '$initial_referrer',
  '$initial_current_url',
];

export default function useAnalytics() {
  const config = useRuntimeConfig().public as unknown as {
    ANALYTICS_ENABLED?: boolean;
    ANALYTICS_ALLOW_DEV?: boolean;
    ANALYTICS_DEPLOYMENT_ID?: string;
    ANALYTICS_SALT?: string;
    ENV_TYPE?: string;
    GITHUB_RUN_NUMBER?: string;
  };

  const deploymentId = config.ANALYTICS_DEPLOYMENT_ID || '';
  const salt = config.ANALYTICS_SALT || '';
  const appVersion = config.GITHUB_RUN_NUMBER || 'Unknown';
  const envType = config.ENV_TYPE || 'dev';
  // Escape hatch to allow analytics on a 'dev' env (e.g. the project's own dev
  // demo). Off by default so local development never sends events accidentally.
  const allowDev = config.ANALYTICS_ALLOW_DEV === true;

  /**
   * Institution opt-in is on AND the deployment is bootstrapped AND no
   * browser-level privacy signal forces us off. Independent of user consent.
   */
  function isInstitutionEnabled(): boolean {
    return config.ANALYTICS_ENABLED === true && !!deploymentId && !!salt;
  }

  /** Hard privacy kill-switches that override everything (incl. user consent). */
  function isForceDisabled(): boolean {
    return (envType === 'dev' && !allowDev) || isDoNotTrack() || isGlobalPrivacyControl();
  }

  /**
   * Whether the consent banner is allowed to appear at all. False when the
   * institution has not opted in, a privacy signal is set, or we are on a
   * sensitive route.
   */
  function canShowConsentBanner(): boolean {
    return isInstitutionEnabled() && !isForceDisabled() && !isSensitiveRoute();
  }

  function getConsent(): AnalyticsConsent {
    return useAnalyticsStore().consent;
  }

  /**
   * All conditions met for actually emitting events. False on sensitive auth
   * routes so no event (and its auto-attached URL) is captured while a URL may
   * still contain an email.
   */
  function isActive(): boolean {
    return isInstitutionEnabled() && !isForceDisabled() && !isSensitiveRoute() && getConsent() === 'granted';
  }

  /**
   * One-way salted hash for any identifier (user / lab / org / workflow id).
   * The salt is private to this composable, so call-sites cannot produce an
   * unsalted hash. Returns '' when analytics is not configured.
   */
  async function hashId(value: string | null | undefined): Promise<string> {
    if (!value || !deploymentId || !salt || !isBrowser() || !window.crypto?.subtle) return '';
    const input = `${value}${deploymentId}${salt}`;
    const bytes = new TextEncoder().encode(input);
    const digest = await window.crypto.subtle.digest('SHA-256', bytes);
    return Array.from(new Uint8Array(digest))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('');
  }

  /**
   * Lazily imports and initialises the PostHog SDK. Safe to call multiple times;
   * it only loads once. No-op (returns null) unless the institution opted in and
   * no privacy signal forces us off.
   */
  async function load(): Promise<PostHogLike | null> {
    if (posthog) return posthog;
    if (!isInstitutionEnabled() || isForceDisabled() || !isBrowser()) return null;
    if (initInFlight) return initInFlight;

    initInFlight = (async () => {
      try {
        // Dynamic import so the SDK is only ever downloaded after the gates pass.
        const module: any = await import('posthog-js');
        const ph = (module.default ?? module) as PostHogLike;

        ph.init(POSTHOG_PROJECT_API_KEY, {
          api_host: POSTHOG_API_HOST,
          ui_host: POSTHOG_UI_HOST,
          // We send explicit, reviewed events only.
          autocapture: false,
          capture_pageview: false,
          // Off because the auto-captured $pageleave attaches the full
          // $current_url (incl. query params like ?email=) on auth routes.
          // Pageviews are emitted manually and sanitized via page().
          capture_pageleave: false,
          disable_session_recording: true,
          persistence: 'localStorage',
          // Defense-in-depth: PostHog auto-attaches URL/host properties to every
          // event. Reduce $current_url / $referrer to a sanitized pathname (no
          // origin, so no hostname leaks; query strings — which can contain
          // emails on auth routes — stripped; identifying segments masked) and
          // drop the host-bearing properties entirely.
          sanitize_properties: (properties: Record<string, unknown>) => {
            const sanitized = { ...properties };
            if (typeof sanitized.$current_url === 'string') {
              sanitized.$current_url = sanitizeUrl(sanitized.$current_url);
            }
            if (typeof sanitized.$referrer === 'string' && sanitized.$referrer !== '$direct') {
              sanitized.$referrer = sanitizeUrl(sanitized.$referrer);
            }
            if (typeof sanitized.$pathname === 'string') {
              sanitized.$pathname = sanitizePath(sanitized.$pathname);
            }
            for (const key of HOST_BEARING_PROPERTIES) {
              delete sanitized[key];
            }
            return sanitized;
          },
          // Start paused; we opt in explicitly once consent is confirmed.
          opt_out_capturing_by_default: true,
          loaded: (loaded: PostHogLike) => {
            posthog = loaded;
            // Super-properties on every event (describe the deployment, not the user).
            loaded.register({
              deployment_id: deploymentId,
              app_version: appVersion,
              env_type: envType,
            });
            // Aggregate per-deployment using PostHog Groups.
            loaded.group('deployment', deploymentId);
            if (getConsent() === 'granted') {
              loaded.opt_in_capturing();
            }
          },
        });
        posthog = ph;
        return ph;
      } catch (error) {
        console.error('Failed to load analytics SDK', error);
        return null;
      } finally {
        initInFlight = null;
      }
    })();

    return initInFlight;
  }

  /** Persists the consent choice to this device and (if signed in) to DynamoDB. */
  async function persistConsent(consent: AnalyticsConsent): Promise<void> {
    useAnalyticsStore().setConsent(consent);
    try {
      const userStore = useUserStore();
      const userId = userStore.currentUserDetails.id;
      if (userId) {
        const { $api } = useNuxtApp();
        await $api.users.updateUser(userId, { AnalyticsConsent: consent });
      }
    } catch (error) {
      // Device-level consent already saved; cross-browser sync is best-effort.
      console.error('Failed to sync analytics consent to profile', error);
    }
  }

  /** User grants consent: persist, load the SDK and start capturing. */
  async function optIn(): Promise<void> {
    await persistConsent('granted');
    const ph = await load();
    ph?.opt_in_capturing();
    // Capture the deferred app_loaded now that we are allowed to.
    track('app_loaded', { app_version: appVersion, env_type: envType });
  }

  /** User revokes consent: stop capturing, flush opt-out, persist denial. */
  async function optOut(): Promise<void> {
    try {
      posthog?.opt_out_capturing();
    } catch (error) {
      console.error('Failed to opt out of analytics', error);
    }
    await persistConsent('denied');
  }

  /** Associates subsequent events with a salted, anonymous user id. */
  async function identify(userId: string | null | undefined): Promise<void> {
    if (!isActive()) return;
    const ph = await load();
    if (!ph) return;
    const hashed = await hashId(userId);
    if (hashed) ph.identify(hashed);
  }

  /** Clears identity (sign-out). */
  function reset(): void {
    try {
      posthog?.reset();
    } catch (error) {
      console.error('Failed to reset analytics identity', error);
    }
  }

  /**
   * Captures a typed analytics event. No-op unless every opt-in gate is open.
   * Property shapes are defined by the shared event taxonomy.
   */
  function track<K extends AnalyticsEventName>(name: K, properties: AnalyticsEventPropertiesMap[K]): void {
    if (!isActive() || !posthog) return;
    try {
      posthog.capture(name, properties as Record<string, unknown>);
    } catch (error) {
      console.error('Failed to capture analytics event', error);
    }
  }

  /** Captures a sanitized pageview (UUID-like path segments masked, no query string). */
  function page(): void {
    if (!isActive() || !posthog || !isBrowser()) return;
    try {
      posthog.capture('$pageview', {
        $pathname: sanitizePath(window.location.pathname || ''),
      });
    } catch (error) {
      console.error('Failed to capture analytics pageview', error);
    }
  }

  return {
    appVersion,
    envType,
    isInstitutionEnabled,
    isForceDisabled,
    canShowConsentBanner,
    isActive,
    getConsent,
    hashId,
    load,
    optIn,
    optOut,
    identify,
    reset,
    track,
    page,
  };
}
