/**
 * Error messages generated by backend and optionally used by frontend logic
 */
export const ERROR_MESSAGES = {
  invitationAlreadyActivated: 'User invitation to access Organization is already activated.',
};
