import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

/**
 * Absolute path to the generated Easy Genomics OpenAPI specification.
 *
 * The spec is the single source of truth for the platform's HTTP routes. It is
 * generated by `generate-openapi.ts` and consumed both by the front-end type
 * generator and — via {@link loadEasyGenomicsApiSpec} — by the back-end CDK
 * `SpecRestApiConstruct` that deploys API Gateway directly from it.
 */
export const EASY_GENOMICS_API_SPEC_PATH = path.join(__dirname, 'easy-genomics-api.yaml');

/**
 * Parses the committed OpenAPI spec into a plain object.
 *
 * `js-yaml` is a shared-lib dependency; exposing the parse here keeps the
 * dependency on the correct side of the pnpm package boundary so the back-end
 * does not need its own copy. The returned document is environment-agnostic and
 * AWS-neutral — all API Gateway extensions are injected downstream at synth.
 */
export function loadEasyGenomicsApiSpec(specPath: string = EASY_GENOMICS_API_SPEC_PATH): Record<string, any> {
  const raw = fs.readFileSync(specPath, 'utf-8');
  return yaml.load(raw) as Record<string, any>;
}
