easy-genomics:
  configurations:
    - dev:
        aws-account-id:
        aws-region:
        env-type:
        application-url:

        # Back-End specific settings
        back-end:
            system-admin-email:
            system-admin-password:
            secret-key:
            test-user-email:
            test-user-password:

        # Front-End specific settings
        front-end:
            # The following Front-End Infrastructure settings will need to be pre-configured in AWS.
            aws-hosted-zone-id:
            aws-hosted-zone-name:
            aws-certificate-arn:

            # The following Front-End Web UI / Nuxt Config settings will need to be sourced from the Back-End deployment.
            aws-cognito-user-pool-id:
            aws-cognito-client-id:
            base-api-url: # TODO: Replace with application-url once APIGateway uses custom domains
            mock-org-id: # TODO: Remove once custom User Authorization logic retrieves OrgIds
