easy-genomics:
  configurations:
    - demo: # Unique 'env-name' identifier for the following collection of configuration settings (e.g. dev, uat, demo, prod)
        # Shared settings common to Back-End and Front-End sub-packages
        aws-account-id: # e.g '123456789'
        aws-region: # e.g. 'us-east-1'
        env-type: # e.g. 'dev' | 'pre-prod' | 'prod'; only 'dev' env-type can have AWS CloudFormation resources destroyed
        app-domain-name: # e.g. 'demo.easy-genomics.myinstitution.org'
        # The following Front-End Infrastructure settings will need to be pre-configured in AWS and defined when 'env-type' is 'pre-prod' or 'prod'.
        aws-hosted-zone-id: # Not required when env-type: 'dev', but must exist for the same app-domain-name if configured
        aws-certificate-arn: # Not required when env-type: 'dev', but must exist for the same app-domain-name if configured

        # Back-End specific settings
        back-end:
            jwt-secret-key: '123e4567-e89b-12d3-a456-426614174000'
            sys-admin-email:  'yoursysadmin@easygenomics.org',
            sys-admin-password: # System Admin Password - must be minimum 8 chars long and contain: 1 number, 1 special char, 1 uppercase letter, 1 lowercase letter
            test-user-email: 'yourtestuser@easygenomics.org'
            test-user-password: # Demo User Password - must be minimum 8 chars long and contain: 1 number, 1 special char, 1 uppercase letter, 1 lowercase letter
